version: '3'

services:
  db:
    container_name: django_db
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "0000"
      MYSQL_DATABASE: "main"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "0000"
    ports:
      - "3315:3306"
    command: ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY '0000';
    command: ALTER USER 'admin'@'%' IDENTIFIED WITH mysql_native_password BY '0000';
  web:
    container_name: django_web
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8005:8000"
    depends_on:
      - db
    links:
      - db:django_db
